on:
  workflow_dispatch:

name: Publish image to GHCR

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"

      - name: Build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64, linux/amd64
          push: true
          tags: ghcr.io/coffee-cup/railway-utils:latest, ghcr.io/coffee-cup/railway-utils:${{ steps.date.outputs.date }}
